[project]
name = "webapp-coolbeans"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.123.9",
    "fastapi-cloud-cli>=0.6.0",
    "mypy==1.19.0",
]
