apiVersion: 1

provisioning:
  dashboards:
    allowUiUpdates: true

datasources:
  - name: TimescaleDB
    type: postgres
    access: proxy
    orgId: 1
    url: timescaledb:5432
    user: admin
    secureJsonData:
      password: "12345678"
    jsonData:
      database: metrics_db
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
    isDefault: true
    editable: true
