version: "3.9"

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: timescaledb
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - timescale_data:/var/lib/postgresql/data
    networks:
      - coolbeans_net
    ports:
      - "5432:5432"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_USER: root
      GF_SECURITY_ADMIN_PASSWORD: root
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - timescaledb
    networks:
      - coolbeans_net
    ports:
      - "${GRAFANA_PORT}:3000"
    restart: unless-stopped
  fastapi:
    build: ../backend
    container_name: fastapi
    networks:
      - coolbeans_net
    ports:
      - "${FASTAPI_PORT}:8000"
    depends_on:
      - timescaledb
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PGHOST: timescaledb
      PGPORT: "5432"
      PGDATABASE: ${POSTGRES_DB}
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      ROSBRIDGE_HOST: host.docker.internal
      ROSBRIDGE_PORT: "1153"
    restart: "no"
  react:
    build: ../frontend
    container_name: react
    networks:
      - coolbeans_net
    ports:
      - "${REACT_PORT}:3000"
    depends_on:
      - fastapi
    restart: unless-stopped

volumes:
  timescale_data:
  grafana_data:

networks:
  coolbeans_net:
    driver: bridge

